---
name: Inspect AI Scheduled Tests

"on":
  schedule:
    # Run every 12 hours
    - cron: "0 */12 * * *"
  push:
    branches:
      - "**" # Run on all branches for testing
    # This is valuable during action development cycle
  workflow_dispatch:
    inputs:
      run_slow_tests:
        description: "Run slow tests"
        required: false
        default: true
        type: boolean
      test_slack_access:
        description: "Test Slack channel access"
        required: false
        default: false
        type: boolean
      inspect_ai_ref:
        description: "inspect_ai branch/tag/commit to checkout"
        required: false
        default: ""
        type: string

jobs:
  slow-tests:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'push' || inputs.run_slow_tests }}
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/${{ github.repository_owner }}/inspect-ai-runner:latest
      options: --privileged -v /var/run/docker.sock:/var/run/docker.sock

    steps:
      # Critical: Setup modern Docker build system
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: |
            network=host
          buildkitd-flags: |
            --allow-insecure-entitlement security.insecure
            --allow-insecure-entitlement network.host

      - name: Update inspect_ai repository
        run: |
          cd /workspace
          git config --global --add safe.directory /workspace
          git fetch origin
          git checkout ${{ inputs.inspect_ai_ref || 'main' }}
          git pull origin ${{ inputs.inspect_ai_ref || 'main' }}

      - name: Get inspect_ai commit info
        id: inspect_commit
        run: |
          cd /workspace
          echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "ref=${{ inputs.inspect_ai_ref || 'main' }}" >> $GITHUB_OUTPUT

      - name: Install/update dependencies
        run: |
          cd /workspace
          python -m pip install --upgrade pip
          pip install --only-binary=all -e ".[dev]"

      - name: Run slow tests
        timeout-minutes: 180
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_PROGRESS: plain
          BUILDX_CACHE_FROM: type=local,src=/tmp/.buildx-cache
          BUILDX_CACHE_TO: type=local,dest=/tmp/.buildx-cache,mode=max
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GROK_API_KEY: ${{ secrets.GROK_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

        run: |
          cd /workspace
          echo "Running slow tests with --runslow flag..."
          pytest --runslow -m slow --runapi -m api --ignore=tests/agent/test_agent_human.py -k "not test_mcp_sampling_fn"

      - name: Report test results to Slack
        if: always() && steps.inspect_commit.outputs.ref == 'main'
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅ Slow Tests Passed' || '🚨 Slow Tests Failed' }}",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "${{ job.status == 'success' && '✅ Slow Tests Passed' || '🚨 Slow Tests Failed' }}"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*Repository:*\n${{ github.repository }}"
                    },
                    {
                      "type": "mrkdwn", 
                      "text": "*Branch:*\n${{ github.ref_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Trigger:*\n${{ github.event_name }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Workflow:*\n<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Run>"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Tested:*\n<https://github.com/UKGovernmentBEIS/inspect_ai/commit/${{ steps.inspect_commit.outputs.sha }}|inspect_ai@${{ steps.inspect_commit.outputs.ref }}#${{ steps.inspect_commit.outputs.short_sha }}>"
                    }
                  ]
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ job.status == 'failure' && '<!channel> The slow tests have failed. Please investigate.' || 'All tests completed successfully! 🎉' }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Actor: ${{ github.actor }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Cleanup Docker resources
        if: always()
        run: |
          docker system prune -f
          docker volume prune -f

  test-slack-access:
    if: ${{ github.event_name == 'workflow_dispatch' && inputs.test_slack_access }}
    runs-on: ubuntu-latest

    steps:
      - name: Test Slack Channel Access
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            🧪 **Slack Integration Test**

            This is a test message to verify GitHub Actions can successfully post to this Slack channel.

            • Repository: ${{ github.repository }}
            • Branch: ${{ github.ref_name }}  
            • Actor: ${{ github.actor }}
            • Run ID: ${{ github.run_id }}

            If you see this message, the integration is working correctly! ✅
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Test Result
        run: |
          echo "✅ Slack channel access test completed successfully!"
          echo "Check your Slack channel for the test message."
