---
name: Inspect AI Scheduled Tests

"on":
  schedule:
    # Run daily at 2 AM UTC
    - cron: "0 2 * * *"
  push:
    branches:
      - "**" # Run on all branches for testing
    # TODO: Comment out the push trigger before merging to main
    # This is only used during action development cycle
  workflow_dispatch:
    inputs:
      run_slow_tests:
        description: "Run slow tests"
        required: false
        default: true
        type: boolean
      run_api_tests:
        description: "Run API tests (requires secrets)"
        required: false
        default: false
        type: boolean

jobs:
  slow-tests:
    if: ${{ github.event_name == 'schedule' || github.event_name == 'push' || inputs.run_slow_tests }}
    runs-on: ubuntu-latest

    steps:
      # Critical: Setup modern Docker build system
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          driver-opts: |
            network=host
          buildkitd-flags: |
            --allow-insecure-entitlement security.insecure
            --allow-insecure-entitlement network.host

      # Verify Docker is working before running tests
      - name: Verify Docker functionality
        run: |
          docker --version
          docker info
          docker buildx version
          docker run --rm hello-world
          echo "✅ Docker is properly configured"

      - name: Checkout inspect_ai repository
        uses: actions/checkout@v4
        with:
          repository: UKGovernmentBEIS/inspect_ai

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install inspect_ai with development dependencies for testing
          pip install -e ".[dev]"

      - name: Run slow tests
        timeout-minutes: 30
        env:
          # Ensure Docker commands get proper output
          PYTHONUNBUFFERED: 1
          # Enable Docker buildkit cache and verbose logging
          DOCKER_BUILDKIT: 1
          # Prevent Docker CLI from buffering output
          DOCKER_CLI_EXPERIMENTAL: enabled
          BUILDKIT_PROGRESS: plain
          # Pass cache mount info to any Docker builds
          BUILDX_CACHE_FROM: type=local,src=/tmp/.buildx-cache
          BUILDX_CACHE_TO: type=local,dest=/tmp/.buildx-cache,mode=max
          # pytest --runslow tests/tools/test_inspect_tool_support.py::test_text_editor_user -v -s --tb=short --capture=no --log-cli-level=DEBUG
        run: |
          echo "Running slow tests with --runslow flag..."
          echo "Docker containers before tests:"
          docker ps -a
          pytest --runslow -m slow --ignore=tests/agent/test_agent_human.py

      - name: Report test results
        if: failure()
        run: |
          echo "::error::Slow tests failed! Check the logs above for details."
          echo "Consider reporting to appropriate channels (e.g., Slack)."
          # TODO: Add Slack notification or other reporting mechanism

      - name: Cleanup Docker resources
        if: always()
        run: |
          docker system prune -f
          docker volume prune -f
